services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - '5000:5000'
    environment:
      MONGODB_URL: mongodb://mongodb:27017/DigitalAcademyDB
      PORT: '5000'
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
