services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
    - /app/node_modules
    - ./backend:/app
    ports:
      - '5000:5000'
    environment:
      MONGODB_URL: mongodb://mongodb:27017/DigitalAcademyDB
      PORT: '5000'
      NODE_ENV: development
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo